import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import { ClerkProvider } from "@clerk/nextjs";
>>>>>>> cdb98252626139dd9dac3b4eba7c7aee07010516

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Palshub",
  description: "Chat at anytime, anywhere, with anyone.",
>>>>>>> cdb98252626139dd9dac3b4eba7c7aee07010516
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
=======
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
>>>>>>> cdb98252626139dd9dac3b4eba7c7aee07010516
  );
}
